# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
#
# SPDX-License-Identifier: curl

name: checksrc

on:
  # Trigger the workflow on push or pull requests, but only for the
  # master branch
  push:
    branches:
      - master
      - '*/ci'
  pull_request:
    branches:
      - master

permissions: {}

jobs:
  all:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: check
        run: git ls-files "*.[ch]" | xargs -n1 ./scripts/checksrc.pl
